
##############################################################################
# scalar values
##############################################################################

# The name of the catalog configuration file to load
catalog : null 
# The name of the model configuration file to load
model : null
# The name of the parameters configuration file to load
parameters : null 
#Name of the modular pipeline to run. If not set, the project pipeline is run 
# by default
pipeline : null 
# Specify a runner that you want to run the pipeline with.
# Available runners: `SequentialRunner`, `ParallelRunner` and `ThreadRunner`
# If not set, `SequentialRunner` will be used.
runner : null 
# Load and save node inputs and outputs asynchronously with threads. 
# If not specified, load and save datasets synchronously
async : False
# Kedro configuration environment name. Defaults to `local`.
env: null 

##############################################################################
# list values

# We can override the value of parameters that expect a list as: 
# python -m eensight from_inputs=[input1,input2]
# No space should exist before or after colons or commas, otherwise, the 
# mapping should be passed as a (double) quoted string:
  # python -m eensight from_inputs="[input1, input2]"
##############################################################################

# A list of dataset names which should be used as a starting point
from_inputs : null 
# A list of dataset names which should be used as an end point
to_outputs : null 
# A list of node names which should be used as a starting point
from_nodes : null 
# A list of node names which should be used as an end point
to_nodes : null 
# A list with node names. The `run` function will run only the nodes with 
# specified names
nodes : null 
# List of tags. Construct a pipeline from nodes having any of these tags
tags : null


##############################################################################
# dictionary values

# We can override the value of arguments that expect a dictionary as: 
# python -m eensight <argument>={key1:value1,key2:value2}
# No space should exist before or after colons or commas, otherwise, the 
# mapping should be passed as a (double) quoted string:
# python -m eensight <argument>="{key1: value1, key2: value2}""
##############################################################################

# A mapping between dataset names and versions to load. Has no effect on 
# data sets without enabled versioning. 
load_versions : null
# Specify extra parameters that you want to pass to the context initializer. 
# The value of these parameters will override the values in the `parameters`
# configuration file
params : null 

##############################################################################
# hydra-specific
##############################################################################

hydra: 
  output_subdir: null
  run:
    dir: .
  sweep:    
    dir: .


