preprocess:
  
  consumption_step:
    no_change_window : 3
    allow_zero       : false
    allow_negative   : false
    trend            : c
    alpha            : 0 
    l1_ratio         : 0
    global_c         : 4
    local_c          : 4
    min_samples      : 0.6

  temperature_step:
    no_change_window : 3
    allow_zero       : true
    allow_negative   : true
    global_c         : 4
    local_c          : 4
    min_samples      : 0.6 
    impute_window    : 6



      
                    
                                                          
                                                          
                                                   