
base_model: towt
pipeline: null 
runner: null 
from_inputs: null 
to_outputs: null 
from_nodes: null 
to_nodes: null 
nodes: null 
tags: 
  - train
  - apply
load_versions: null
extra_params: null 



